### ISSUE TITLE
images not available

### ISSUE THREAD

**Issue by rodrigour** [OpenAgricultureFoundation/Tomato_Experiment#1]
Hi, the images are not available in https://storage.googleapis.com/openag-v1-images/.

**Comment by srmoore** [comment]
The backend system is no longer available. I'll update this once I have figured out a hosting solution for the images for the dataset. (It's a rather large amount of data.)

**Comment by rodrigour** [comment]
Thanks, is there any way you can share only the images for the Control environment? in a zip file of gmail would work.

**Comment by srmoore** [comment]
Unfortunately I believe it would still be too big of a file to send via gmail. I'm almost finished with uploading the 45GB tar.gz file to a site to allow someone to download the entire set of images.

**Comment by srmoore** [comment]
The images are located at http://openag.srmoore.org/openag_datasets/openag_tomato_experiment_images/openag_tomato_experiment_images.tar.gz 

The file has a SHA256 checksum of ead45cc2c7de0cc7ad1460d4e07859648923bf07aba7a2a3f2d9aacf00f85fe0

**Comment by srmoore** [comment]
Closing this issue now that a pointer to the archive has been added to the `raw_data/README.md`

**Comment by srmoore** [comment]
@rodrigour  Please let me know if you have downloaded the file. After you have, I am going to shut off public access temporarily, as the way I'm hosting it isn't sustainable for public consumption. (I'll either resort to one time links, or find another hosting solution.  Thanks!

**Comment by srmoore** [comment]
New location for the images is https://archive.org/details/openag_tomato_experiment_images.tar
 closing the issue again.
